### ISSUE TITLE
Blackbone

### ISSUE THREAD

**Issue by ZoloftCSGO** [b1scoito/cozinha_loader#10]
So, I've added the include directorys as follows
C:\Users\theor\Desktop\Blackbone-master\src\BlackBone;$(IncludePath) <-- The include directory
![image](https://user-images.githubusercontent.com/97027698/147941274-30e9e02c-9786-40ec-87b1-410a2eade53e.png)

C:\Users\theor\Desktop\Blackbone-master\LIB;$(LibraryPath) <--- The libary directory
![image](https://user-images.githubusercontent.com/97027698/147941294-aedf5c68-12ce-43d9-9b2e-096ff925468f.png)

And i'm still getting errors.

**Comment by b1scoito** [comment]
Please do not create another issue for the same problem, comment on the already created issue.

The issues section are for issues related with the loader.
