### ISSUE TITLE
Erro a compilar

### ISSUE THREAD

**Issue by ghost** [b1scoito/cozinha_loader#13]
Olá, estou a ter error LNK1181 cannot open infput file"BlackBone.lib", quando tento compilar

**Comment by b1scoito** [comment]
https://github.com/b1scoito/cozinha_loader#compiling

**Comment by ghost** [comment]
Segui tudo direito.  Acho que estou a colocar mal o caminho até a library.

**Comment by b1scoito** [comment]
Você precisa compilar a library e incluir no projeto.

**Comment by ghost** [comment]
estou a ficar doido, ja tentei de tudo nada funciona. onde coloco a library?

**Comment by ghost** [comment]
Acho que já adicionei, porem estou a ter 4 erros 
![image](https://user-images.githubusercontent.com/80291302/149234561-de31250c-e1e8-4d19-a770-c3aab557c340.png)

**Comment by kajakoenders1** [comment]
> Acho que já adicionei, porem estou a ter 4 erros ![image](https://user-images.githubusercontent.com/80291302/149234561-de31250c-e1e8-4d19-a770-c3aab557c340.png)

Inlude the library in ur project.
