### ISSUE TITLE
About Bypassing injection block by csgo

### ISSUE THREAD

**Issue by jackKiZhu** [b1scoito/cozinha_loader#16]
About Bypassing injection block by csgo (-allow_third_party_software)
If I quit the game, do I need to call this function the next time I open the game?

**Comment by b1scoito** [comment]
What?

**Comment by jackKiZhu** [comment]
> What?

std::uint8_t restore[5];
			std::memcpy( restore, ntopenfile_ptr, sizeof( restore ) );

			const auto result = bb_proc.memory().Write( (std::uintptr_t) ntopenfile_ptr, restore );

This Bypassing injection block, after the game exits, will it take effect the next time you enter the game?

**Comment by b1scoito** [comment]
Your question doesn't make sense. This whole routine is executed once the game launches. If you open it again it'll not get executed unless you use the injector again.
