### ISSUE TITLE
make detected cheat undetectable ?

### ISSUE THREAD

**Issue by razeNFR** [b1scoito/cozinha_loader#20]
This Injector can make a .DLL of detected cheat undetectable by vac ?

**Comment by b1scoito** [comment]
Your question doesn't make sense.

**Comment by razeNFR** [comment]
Yeah, sorry my english is very bad but, i wanna if we use a cheat, maybe "osiris" who is detected since long time ago, if we can get banned with your injector ?

**Comment by b1scoito** [comment]
I'm not responsible for any issue related to the DLL you're injecting.
