### ISSUE TITLE
cant build.

### ISSUE THREAD

**Issue by 90th** [b1scoito/cozinha_loader#22]
Located the blackbone files, but getting 300 more errors? 
![image](https://user-images.githubusercontent.com/80871202/171139590-fdf5db2e-16cc-4d00-9803-59eb03aa3ed8.png)
![image](https://user-images.githubusercontent.com/80871202/171139642-e60c096c-1242-4202-b878-df658763f333.png)

**Comment by b1scoito** [comment]
I'm not sure what those can be, but my project certainly isn't

**Comment by 90th** [comment]
located in your external dependencies

**Comment by b1scoito** [comment]
Sorry I didn't understand?

**Comment by 90th** [comment]
![image](https://user-images.githubusercontent.com/80871202/171329160-4f115e7a-004d-42eb-aeec-1ac67f1a94a9.png)

**Comment by b1scoito** [comment]
That has nothing to do with my project

**Comment by 90th** [comment]
Whats your general properties, the same?

**Comment by b1scoito** [comment]
Well, if you didn't change anything, it should work just fine.

**Comment by 90th** [comment]
Only thing i changed was the location of Blackbone

🤔

**Comment by b1scoito** [comment]
Probably something wrong with your toolset

**Comment by 90th** [comment]
Which toolset are you using for the project? v143?

**Comment by b1scoito** [comment]
Yeah, if I recall correctly

**Comment by 90th** [comment]
Yeah i figured out my problem, im a dumbass and forgot to include the BlackBone.lib 🤦🏻 

sorry for the waste of time but thank you for trying to help, your response time is gnarly !
