### ISSUE TITLE
vac3_data

### ISSUE THREAD

**Issue by 90th** [b1scoito/cozinha_loader#24]
Do i need to update the vac3_data?
it seems to fail to inject the vac bypass
![image](https://user-images.githubusercontent.com/80871202/171813822-5eae2ead-c4c4-41e9-9b4e-9de4685543ee.png)

**Comment by b1scoito** [comment]
What's your call stack

**Comment by 90th** [comment]
![image](https://user-images.githubusercontent.com/80871202/171814066-29e90fca-89cf-45b6-b948-9500ef678f6f.png)

(off topic but are you even real damn you respond insanely fast)

**Comment by b1scoito** [comment]
Please run in Debug not in Release and show again

**Comment by 90th** [comment]
Debug seems to cause tons of errors, i assume its not including the blackbone files and stuff correctly

![image](https://user-images.githubusercontent.com/80871202/171814580-ecbd92ce-5eec-45d8-a301-018cc8d863ad.png)

**Comment by b1scoito** [comment]
You need to include both Release and Debug BlackBone libraries and source files respectively

**Comment by 90th** [comment]
![image](https://user-images.githubusercontent.com/80871202/171817906-9ac20ad8-1676-4d7e-82b0-bf3625ff3c3d.png)
any idea?

**Comment by b1scoito** [comment]
Mismatch between BlackBone's Runtime Library and my project's.
