### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by aldias14** [b1scoito/cozinha_loader#25]
When I run it, the console opens, but in steam nothing happens, I mean I haven't this logs like "VAC3 loading module cr32..."

![147694699-226bb43d-7928-407a-91fd-af0930818a78](https://user-images.githubusercontent.com/75922463/184506228-fe6c0279-959f-45b3-ae62-27c05629f2c0.png)
.

**Comment by b1scoito** [comment]
What do you mean, I don't understand exactly what's your question?

**Comment by aldias14** [comment]
![184506228-fe6c0279-959f-45b3-ae62-27c05629f2c0](https://user-images.githubusercontent.com/75922463/184510170-88dc2236-7c27-431c-b040-0f31a2148615.png)

I mean that when dll is injecting I don't have this steam window with log. So is it still working?

**Comment by b1scoito** [comment]
Oh, I understand you now, yeah, it's still working, it's only that I have the Steam console opened on that image. You can open it by executing this link on Win + R: `steam://open/console`, you will be able to see the VAC3 bypass logs from now on.

**Comment by aldias14** [comment]
Did you check this bypass? How long is there no ban on the account? Is there a certain delay before getting a VAC ban?

**Comment by aldias14** [comment]
And is it better to use default manual map or blackbone which you have in this loader? Is it safe to close/open automatically steam/csgo processes?

**Comment by aldias14** [comment]
And last questions, maybe you know better bypass than this? What is better to use danielkrupinski bypass or this?

**Comment by b1scoito** [comment]
> Did you check this bypass? How long is there no ban on the account? Is there a certain delay before getting a VAC ban?

It's a bypass, so it's not meant to get you _banned_.

> And is it better to use default manual map or blackbone which you have in this loader? Is it safe to close/open automatically steam/csgo processes?

There's only one method of injection, which is BlackBone's Manual map, as far as I know, it is safe to open these processes automatically.

> And last questions, maybe you know better bypass than this? What is better to use danielkrupinski bypass or this?

You use what you deem good for you. If you think that X bypass is better, you can change it in the source code and compile yourself. I personally like the way we bypass it.

**Comment by aldias14** [comment]
For example vac updated and signatures changed. How can I update signatures in hooks.cpp?

**Comment by b1scoito** [comment]
By changing them. Otherwise we'll push an update; And the right repository to be asking this sorta stuff is here: https://github.com/zyhp/vac3_inhibitor

**Comment by aldias14** [comment]
Ok close
