### ISSUE TITLE
Can't compile)

### ISSUE THREAD

**Issue by aldias14** [b1scoito/cozinha_loader#26]
I want to add some new lines of code, but I must have Blackbone include/lib paths. I tried to compile it from blackbone github, but fail. Can you send your blackbone static library release? 
![image](https://user-images.githubusercontent.com/75922463/184873659-fd799318-3311-402a-949a-a58ad528ceb1.png)

**Comment by b1scoito** [comment]
All you need is to compile the BlackBone library in Release for `x86`

**Comment by aldias14** [comment]
Okay as I said before I compiled it. Which files now I need? 
![image](https://user-images.githubusercontent.com/75922463/184952757-bb79f353-1c0f-4b7c-8a36-5aa2d79afd57.png)

**Comment by aldias14** [comment]
I found include folder, but where is the lib folder?

**Comment by aldias14** [comment]
Pls help

**Comment by b1scoito** [comment]
> I found include folder, but where is the lib folder?

The lib folder is the one you just built.
