### ISSUE TITLE
Pch.hpp

### ISSUE THREAD

**Issue by coercing** [b1scoito/cozinha_loader#28]
![image](https://user-images.githubusercontent.com/108820480/185431917-0788d828-95c8-44f7-8513-d11db4337b4d.png)

This Error Is All I See To Get When I Try To Build It. When I Add The '#include "pch.hpp" it dont work still. Any Advice?

**Comment by b1scoito** [comment]
You cannot include blackbone directly onto this project.

**Comment by coercing** [comment]
how do i add blackbone without it being direct?

**Comment by b1scoito** [comment]
I made a quick tutorial to help those who are having issues to compile BlackBone: https://github.com/b1scoito/cozinha_loader#how-to-compile-blackbone-and-include-it
