### ISSUE TITLE
Cant pick a team

### ISSUE THREAD

**Issue by Intel-Ixchel** [b1scoito/cozinha_loader#29]
Hey small thing, I get ingame and I cant pick a team only happens when I use the loader, guessing its a vac thing? Any help or fixes are appreciated

**Comment by b1scoito** [comment]
It's most certainly not related to my loader or the vac3 bypass. Might be an issue with your system/cheat you're using.

**Comment by Intel-Ixchel** [comment]
Its not, its only when using the loader, everything else runs correctly otherwise

**Comment by b1scoito** [comment]
It doesn't make any sense, my loader doesn't do anything that might cause that behavior.

**Comment by Intel-Ixchel** [comment]
Hmm ran a diff cheat same issue

**Comment by b1scoito** [comment]
Probably a issue on your end, try without my loader.

**Comment by Intel-Ixchel** [comment]
I have both run fine with CSGhost

**Comment by b1scoito** [comment]
I have no idea then, but it is most certainly not caused by my loader, it doesn't have anything to do with this behavior.
