### ISSUE TITLE
Some computers cannot be injected

### ISSUE THREAD

**Issue by java17lzh** [b1scoito/cozinha_loader#30]
After steam is started, the program automatically closes, and injection is not used. How to solve this problem?

**Comment by b1scoito** [comment]
Please check if in your config you configured it to only inject on steam.

**Comment by Sp1ky1** [comment]
Well isn't injecting for me in steam it just says failed to inject

**Comment by b1scoito** [comment]
> Well isn't injecting for me in steam it just says failed to inject

Can you please show me your config and the console output?
