### ISSUE TITLE
Errors of Blackbone 

### ISSUE THREAD

**Issue by xXxNozz4rrxXx** [b1scoito/cozinha_loader#32]
error C2275: 'blackbone::_UNICODE_STRING_T<uint32_t>::type': expected an expression instead of a type an error when i build the lib

i got an errors without i modify something , like process is unidentified  UNICODE STING of duplicate and more

**Comment by xXxNozz4rrxXx** [comment]
>RemoteLocalHook.cpp
1>C:\Users\Nozz4rr\Desktop\Blackbone-exceptions\src\BlackBone\Process\ProcessModules.cpp(423,65): error C2275: 'blackbone::_UNICODE_STRING_T<uint32_t>::type': expected an expression instead of a type
1>C:\Users\Nozz4rr\Desktop\Blackbone-exceptions\src\BlackBone\Process\ProcessModules.cpp(435,38): message : see reference to function template instantiation 'auto blackbone::ProcessModules::Inject::<lambda_1>::operator ()<blackbone::_UNICODE_STRING32>(_T1 &) const' being compiled
1>        with
1>        [
1>            _T1=blackbone::_UNICODE_STRING32
1>        ]
1>C:\Users\Nozz4rr\Desktop\Blackbone-exceptions\src\BlackBone\Process\ProcessModules.cpp(423,30): error C2672: 'blackbone::MemBlock::ptr': no matching overloaded function found
1>C:\Users\Nozz4rr\Desktop\Blackbone-exceptions\src\BlackBone\Process\MemBlock.h(269,7): message : could be 'T blackbone::MemBlock::ptr(void) const' (compiling source file Process\ProcessModules.cpp)
1>C:\Users\Nozz4rr\Desktop\Blackbone-exceptions\src\BlackBone\Process\ProcessModules.cpp(423,65): message : 'blackbone::MemBlock::ptr': invalid template argument for 'T', type expected
1>C:\Users\Nozz4rr\Desktop\Blackbone-exceptions\src\BlackBone\Process\ProcessModules.cpp(423,65): error C2275: 'blackbone::_UNICODE_STRING_T<uint64_t>::type': expected an expression instead of a type
1>C:\Users\Nozz4rr\Desktop\Blackbone-exceptions\src\BlackBone\Process\ProcessModules.cpp(440,38): message : see reference to function template instantiation 'auto blackbone::ProcessModules::Inject::<lambda_1>::operator ()<blackbone::_UNICODE_STRING64>(_T1 &) const' being compiled
1>        with
1>        [
1>            _T1=blackbone::_UNICODE_STRING64
1>        ]
1>RemoteMemory.cpp

**Comment by xXxNozz4rrxXx** [comment]
![image](https://user-images.githubusercontent.com/76511149/217237858-6533c3b6-ecd4-4ee5-93d7-5224b4b1e774.png)

**Comment by b1scoito** [comment]
https://github.com/DarthTon/Blackbone/issues/503
