### ISSUE TITLE
A mistake I don't know if it's my mistake

### ISSUE THREAD

**Issue by zhongmof** [b1scoito/cozinha_loader#34]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “BlackBone/Process/Process.h”: No such file or directory (编译源文件 injection.cpp)	cozinha_loader	C:\Users\djh13\Desktop\cozinha_loader-1.14\cozinha_loader\injection.hpp	6

**Comment by b1scoito** [comment]
https://github.com/b1scoito/cozinha_loader#how-to-compile-blackbone-and-include-it
