### ISSUE TITLE
Make a injection with a dll inside the exe

### ISSUE THREAD

**Issue by parvarti** [b1scoito/cozinha_loader#4]
do u have any ideas to make some resource file with a dll and push it to injection?
i am new dev in c++, any help will be great

**Comment by b1scoito** [comment]
Seeing the arguments that the function [`read_file_to_memory`](https://github.com/b1scoito/cozinha_loader/blob/main/cozinha_loader/utils.hpp#L28) takes it's easy to understand how to embed the DLL inside an array of bytes of the binary.

You will need to make an `unsigned char` array, as made [here](https://github.com/b1scoito/cozinha_loader/blob/main/cozinha_loader/vac3_data.hpp)
And write it into an `std::vector` like [this](https://github.com/b1scoito/cozinha_loader/blob/main/cozinha_loader/injection.cpp#L59).

**Comment by parvarti** [comment]
i will try
thank you <3

**Comment by parvarti** [comment]
one more thing
which program did u use for convert the dll in a unsigned char array?
