### ISSUE TITLE
blackbone.lib won't open

### ISSUE THREAD

**Issue by TheExecutorM** [b1scoito/cozinha_loader#7]
hi blackbone.lib won't open pls help me

**Comment by b1scoito** [comment]
Please be more clear, I didn't understand

**Comment by TheExecutorM** [comment]
I'm Turkish, I'm using translating. When compiling vac bypass loader, it says blackbone.lib does not open, I need help

**Comment by b1scoito** [comment]
You need to include the BlackBone library in the project.

**Comment by TheExecutorM** [comment]
I don't know how to do it, can you tell me a video or a short summary, link to your library please?

**Comment by TheExecutorM** [comment]
help pls

**Comment by b1scoito** [comment]
Learn the C++ configuration options
