### ISSUE TITLE
Crash when inject

### ISSUE THREAD

**Issue by eniorJR** [b1scoito/cozinha_loader#8]
Game crash and close when i try to inject. 
Any idea?

**Comment by b1scoito** [comment]
Do you think it's related to the loader or the DLL you're trying to inject?

**Comment by eniorJR** [comment]
I think is problem of the loader, cause i tried with 3 or 4 dll and doesn't wort, is working for you?

**Comment by b1scoito** [comment]
What's the error you get?

**Comment by eniorJR** [comment]
I'm not getting any errors, the game just hangs and closes.
The injector shows a correct message but the game closes.

**Comment by eniorJR** [comment]
Im sorry, i try with other dll and it works, i thinks Valve fuk my dll's, srry.

**Comment by b1scoito** [comment]
This is an issue with the DLL you're trying to inject, not an issue with the loader.
