### ISSUE TITLE
Failure to build

### ISSUE THREAD

**Issue by ZoloftCSGO** [b1scoito/cozinha_loader#9]
Hi,
I'm having trouble building the project.
How exactly do I add the libary files from blackbone. Any help is appreciated.

**Comment by b1scoito** [comment]
Please read the readme

**Comment by ZoloftCSGO** [comment]
I have read the readme.

**Comment by b1scoito** [comment]
It says to compile the BlackBone library and include the library (.lib) and the BlackBone include directory on the project configuration, have you done that? What's the issue you're facing with? Please be more specific

**Comment by ZoloftCSGO** [comment]
I've never added a libary to a project file before, is there any chance you can guide me?

**Comment by b1scoito** [comment]
https://docs.microsoft.com/en-us/cpp/build/adding-references-in-visual-cpp-projects?view=msvc-170
https://www.learncpp.com/cpp-tutorial/a2-using-libraries-with-visual-studio-2005-express/
https://youtu.be/or1dAmUO8k0

**Comment by ZoloftCSGO** [comment]
My apologises, I didn't realise I could still reply to this one.
C:\Users\theor\Desktop\Blackbone-master\src\BlackBone;$(IncludePath) was the include path I put in the project.
![image](https://user-images.githubusercontent.com/97027698/147941592-a4d89d38-23a1-47fd-82c5-e4d01fc53ce7.png)
![image](https://user-images.githubusercontent.com/97027698/147941617-0cb00fd1-3ec0-4b31-adb7-de9c69488d78.png)

and the libary path was
C:\Users\theor\Desktop\Blackbone-master\LIB;$(LibraryPath)
![image](https://user-images.githubusercontent.com/97027698/147941682-8fc1594a-ebb4-480c-b72f-89d47f07e026.png)

**Comment by b1scoito** [comment]
Almost right, you got to compile the BlackBone project in both Debug and Release and include them in the project with their respective Configurations (Debug and Release), this way the `.lib` file will be generated... The include directory is wrong, it has to be the root directory from the git clone (tl;dr everything inside `src/`).

**Comment by ZoloftCSGO** [comment]
Hi,
I've moved the blackbone include directory.
![image](https://user-images.githubusercontent.com/97027698/147943037-7718f6c9-397f-411f-9a4f-30e8c7b5283b.png)
![image](https://user-images.githubusercontent.com/97027698/147943041-2bf5d4be-df65-4f9c-a5a0-176a40e9f3aa.png)
But i'm still confused by what you mean with "Compile the BlackBone project in both Debug and Release and include them in the project with their respective Configurations (Debug and Release), this way the .lib file will be generated."
![image](https://user-images.githubusercontent.com/97027698/147943152-f11ee3ca-4a17-4618-bbb3-046995b08db8.png)
I compiled both release and debug versions.
